### PR TITLE
Added modules for canadian provinces

### PR DESCRIPTION
**Pull request by sam-gagnon**
Since every canadian province has their own format for citing regulations, I had to make a new module for each.

### CODE REVIEW

**Comment by bwiernik** [comment]
Just to confirm, do these each validate?

**Comment by sam-gagnon** [comment]
Yes, I created style tests for regulations from each province, and they all test correctly.

Edit: If you want to test them for yourself, you can find them here : https://github.com/Droitslinguistiques/jm-style-tests under my jm-mcgill style. They are the "regulation" test group.

**Comment by georgd** [comment]
I looked through the files and they all validate. But it seems to me that some contents of `juris-ca+nb.csl` and `juris-ca+nl.csl` are swapped. The latter redefines the term `rule` as “Règl du N-B” which I’d rather expect in the New Brunswick module.

**Comment by sam-gagnon** [comment]
You are correct. That is leftover junk code from when I copy/pasted to quickly make all of the modules.

Originally, I was going to have the part "NB Reg" or "Règle du NB" render using terms, to prevent error due to incorrect user input. That is what that code is from.

However, I realized that in some modules, different formats are required based on whether the regulations have been revised into a consolidated volume or not. Newfoundland for example takes "CNLR" if revised and "NLR" if unrevised. 

Given that both the revised and unrevised regulations have the same components (container-title, number, volume), I wasn't able to differentiate which term to render. As a result, I removed all terms from all modules (or at least attempted to, as soon by this leftover code) and instead relied on the user to input the correct "CNLR" or "NLR" in the "container-title" field themselves.

Not an ideal solution, but the best that I was able to come up with,

**Comment by bwiernik** [comment]
Let me know when you're ready.

**Comment by sam-gagnon** [comment]
Sorry, yes, I made the modifications that Georg recommended yesterday. All the commits from today were me having a hard with my repository setup. Everything should be good now. 

Btw, are you also a maintainer on the translator or the LRR repositories? I have commits to both of those that have been awaiting review for a while. I know Frank is occupied with life though, so I'm not in a hurry.

**Comment by bwiernik** [comment]
Sure, ping me

**Pull request merged**
