### PR TITLE
Update to style module: juris-eu.int.csl

### PR DESCRIPTION
**Pull request by alexanderschuster77**
Pull request automatically generated by Juris-M

### CODE REVIEW

**Comment by alexanderschuster77** [comment]
The style is not final! I thought submit.means save to my github account
alexander

Le mardi 6 septembre 2016, Frank Bennett notifications@github.com a
écrit :

**Comment by fbennett** [comment]
Ha. You did the right thing, but we need a concept of final clearance in the release protocol, don't we? Sorry for the misstep.

I'll revert the changes in master and re-release the FF plugin today. The JM Standalone releases that contain it will be reverted when I get to the office on Monday.

**Comment by fbennett** [comment]
Reverted in the Myles plugin. Submissions should continue to work smoothly at your end.

Thanks for your work on EU sources -- I'll be more careful about checking in contributions from now on!

**Comment by alexanderschuster77** [comment]
Sorry about that! The guidelines and tutorial should be corrected,
otherwise I fear others may misinterpret the SUBMIT button.
I might need some help to finalize the tutorial. Per se the new citation
standard is very clearly stated here:
http://curia.europa.eu/jcms/jcms/P_125997/en/

Alexander

2016-09-09 23:41 GMT+02:00 Frank Bennett notifications@github.com:

**Pull request merged**
